nelmio_api_doc:
    documentation:
        info:
            title: GOT Characters API
            description: This API includes several endpoints to execute CRUD interactions!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!api/doc$) # Accepts routes under /api except /api/doc
